#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'src', 'data', 'pseo');

function wc(t) { return t.trim().split(/\s+/).filter(w => w.length > 0).length; }

// [slug, topicEN, topicTR, topicFR, topicRU]
const FAQS = [
  ['faq-food-import','Food Product Import','Gida Urunu Ithalati','Importation de Produits Alimentaires','Импорт продовольственных товаров',
   '/trade/import/food-grains,/trade/import/food-dairy,/trade/customs/customs-food-safety'],
  ['faq-textile-import','Textile Import','Tekstil Ithalati','Importation de Textiles','Импорт текстиля',
   '/trade/import/textile-fabrics,/trade/import/textile-ready-to-wear,/trade/customs/customs-textile-regulations'],
  ['faq-machinery-import','Machinery Import','Makine Ithalati','Importation de Machines','Импорт оборудования',
   '/trade/import/machinery-industrial,/trade/import/machinery-agricultural,/trade/customs/customs-machinery-standards'],
  ['faq-chemicals-import','Chemicals Import','Kimyasal Madde Ithalati','Importation de Produits Chimiques','Импорт химической продукции',
   '/trade/import/chemicals-industrial,/trade/import/chemicals-petrochemicals,/trade/customs/customs-chemicals-reach'],
  ['faq-construction-import','Construction Materials Import','Insaat Malzemesi Ithalati','Importation de Materiaux de Construction','Импорт строительных материалов',
   '/trade/import/construction-building-materials,/trade/import/construction-steel,/trade/customs/customs-eu'],
  ['faq-raw-materials-import','Raw Materials Import','Hammadde Ithalati','Importation de Matieres Premieres','Импорт сырья',
   '/trade/import/raw-metals,/trade/import/raw-minerals,/trade/customs/customs-eu'],
  ['faq-electronics-import','Electronics Import','Elektronik Ithalati','Importation dElectronique','Импорт электроники',
   '/trade/import/electronics-components,/trade/import/electronics-consumer,/trade/customs/customs-eu'],
  ['faq-automotive-import','Automotive Import','Otomotiv Ithalati','Importation Automobile','Импорт автомобильной продукции',
   '/trade/import/auto-parts,/trade/import/auto-commercial-vehicles,/trade/customs/customs-eu'],
  ['faq-customs-procedures','Customs Procedures','Gumruk Islemleri','Procedures Douanieres','Таможенные процедуры',
   '/trade/customs/customs-eu,/trade/customs/customs-middle-east,/trade/customs/customs-russia-cis'],
  ['faq-documentation','Trade Documentation','Ticaret Belgeleri','Documentation Commerciale','Торговая документация',
   '/trade/customs/customs-eu,/trade/customs/customs-food-safety,/trade/customs/customs-dangerous-goods'],
  ['faq-shipping-logistics','Shipping and Logistics','Nakliye ve Lojistik','Expedition et Logistique','Доставка и логистика',
   '/trade/country/germany,/trade/country/russia,/trade/country/united-states'],
  ['faq-payment-terms','Payment Terms','Odeme Kosullari','Conditions de Paiement','Условия оплаты',
   '/trade/country/germany,/trade/country/iraq,/trade/country/china'],
];

function buildFAQ(f) {
  const [slug, topicEN, topicTR, topicFR, topicRU, linksStr] = f;
  const links = linksStr.split(',').map(href => ({ label: href.split('/').pop().replace(/-/g,' '), href }));

  // Generate 10 Q&A pairs, each with 40-60 word answers
  const sectorWord = topicEN.toLowerCase().replace(' import','').replace(' and ','');
  const questions = [];

  const qTemplates = [
    {q:{tr:`Turkiyeden ${topicTR.toLowerCase()} icin hangi belgeler gereklidir`,en:`What documents are required for ${topicEN.toLowerCase()} from Turkey`,fr:`Quels documents sont necessaires pour ${topicFR.toLowerCase()} depuis la Turquie`,ru:`Какие документы необходимы для ${topicRU.toLowerCase()} из Турции`},
     a:{tr:`Turkiyeden ${topicTR.toLowerCase()} icin ticari fatura yukleme listesi mense sahadetnamesi gumruk beyannamesi ve urune ozel sertifikalar gerekmektedir. Helal sertifikasi saglik belgesi ve kalite test raporlari da talep edilebilir. Toko Trading tum belgelendirme surecinde alicilara destek saglamaktadir.`,en:`For ${topicEN.toLowerCase()} from Turkey you need a commercial invoice packing list certificate of origin customs declaration and product-specific certifications. Halal certification health certificates and quality test reports may also be required depending on the destination country. Toko Trading assists buyers throughout the entire documentation process.`,fr:`Pour ${topicFR.toLowerCase()} depuis la Turquie vous avez besoin dune facture commerciale dune liste de colisage dun certificat dorigine dune declaration douaniere et de certifications specifiques au produit. Toko Trading accompagne les acheteurs tout au long du processus de documentation.`,ru:`Для ${topicRU.toLowerCase()} из Турции необходимы коммерческий счёт-фактура упаковочный лист сертификат происхождения таможенная декларация и сертификаты специфичные для продукции. Сертификация Халяль медицинские сертификаты и протоколы испытаний качества также могут потребоваться. Toko Trading оказывает содействие покупателям на протяжении всего процесса документооборота.`}},
    {q:{tr:`Turkiyeden ${topicTR.toLowerCase()} icin minimum siparis miktari nedir`,en:`What is the minimum order quantity for ${topicEN.toLowerCase()} from Turkey`,fr:`Quelle est la quantite minimale de commande pour ${topicFR.toLowerCase()} depuis la Turquie`,ru:`Каков минимальный объём заказа для ${topicRU.toLowerCase()} из Турции`},
     a:{tr:`Minimum siparis miktari urun turune ve ureticiye gore degismektedir ancak genel olarak bir konteyner dolumu olan 20 veya 40 feet konteyner standart kabul edilmektedir. Bazi ureticiler daha kucuk partiler icin de uretim yapabilmektedir. Toko Trading farkli ureticilerden gelen partileri birlestirerek kucuk hacimli siparisler icin cozum sunabilmektedir.`,en:`Minimum order quantities vary depending on the product type and manufacturer but generally one full container load of 20 or 40 feet is considered standard. Some manufacturers can produce smaller batches for initial trial orders. Toko Trading can consolidate orders from different manufacturers to provide solutions for small-volume orders enabling businesses of all sizes to import from Turkey.`,fr:`Les quantites minimales de commande varient selon le type de produit et le fabricant mais en general un conteneur complet de 20 ou 40 pieds est considere comme standard. Certains fabricants peuvent produire de plus petits lots. Toko Trading peut consolider les commandes de differents fabricants pour fournir des solutions pour les commandes de petit volume.`,ru:`Минимальные объёмы заказа варьируются в зависимости от типа продукции и производителя но как правило стандартом считается полная контейнерная загрузка 20 или 40 футов. Некоторые производители могут выпускать меньшие партии для пробных заказов. Toko Trading может консолидировать заказы от разных производителей предоставляя решения для заказов небольшого объёма.`}},
    {q:{tr:`Turkiyeden ${topicTR.toLowerCase()} ne kadar surer`,en:`How long does ${topicEN.toLowerCase()} from Turkey take`,fr:`Combien de temps prend ${topicFR.toLowerCase()} depuis la Turquie`,ru:`Сколько времени занимает ${topicRU.toLowerCase()} из Турции`},
     a:{tr:`Toplam sure genellikle siparis onayindan teslimata kadar 4 ila 8 hafta arasinda degismektedir. Uretim suresi urun tipine gore 2-4 hafta transit suresi hedef ulkeye gore 3-25 gun ve gumrukleme islemleri 2-5 gun surmektedir. Toko Trading deneyimli lojistik ekibi ile bu sureleri optimize etmekte ve gecikmeleri en aza indirmektedir.`,en:`The total timeline generally ranges from 4 to 8 weeks from order confirmation to delivery. Production time takes 2 to 4 weeks depending on product type transit time ranges from 3 to 25 days depending on the destination country and customs clearance procedures take 2 to 5 business days. Toko Trading optimizes these timelines with its experienced logistics team and minimizes any potential delays.`,fr:`Le delai total varie generalement de 4 a 8 semaines de la confirmation de commande a la livraison. Le temps de production prend 2 a 4 semaines selon le type de produit le transit de 3 a 25 jours selon le pays de destination et le dedouanement de 2 a 5 jours ouvrables. Toko Trading optimise ces delais avec son equipe logistique experimentee.`,ru:`Общий срок обычно составляет от 4 до 8 недель от подтверждения заказа до доставки. Время производства занимает от 2 до 4 недель в зависимости от типа продукции время транзита составляет от 3 до 25 дней в зависимости от страны назначения а таможенное оформление занимает от 2 до 5 рабочих дней. Toko Trading оптимизирует эти сроки благодаря опытной логистической команде и минимизирует возможные задержки.`}},
    {q:{tr:`Turkiyeden ${topicTR.toLowerCase()} icin hangi odeme yontemleri kabul edilir`,en:`What payment methods are accepted for ${topicEN.toLowerCase()} from Turkey`,fr:`Quels modes de paiement sont acceptes pour ${topicFR.toLowerCase()} depuis la Turquie`,ru:`Какие способы оплаты принимаются для ${topicRU.toLowerCase()} из Турции`},
     a:{tr:`Uluslararasi ticarette en yaygin odeme yontemleri akreditif vesaik mukabili odeme banka havalesi ve pesin odemedir. Ilk kez calisilan tedarikcierde akreditif en guvenli yontemdir. Uzun sureli is iliskilerinde acik hesap veya taksitli odeme de mumkun olabilir. Toko Trading musteri ve tedarikci arasinda en uygun odeme yapisini kurarak her iki tarafin da guvenligini saglamaktadir.`,en:`The most common payment methods in international trade include letter of credit documentary collection bank wire transfer and advance payment. For first-time supplier relationships letter of credit is the safest method providing protection for both buyer and seller. In established long-term business relationships open account or installment payment arrangements may also be possible. Toko Trading helps establish the most suitable payment structure between client and supplier ensuring security for both parties involved in the transaction.`,fr:`Les modes de paiement les plus courants dans le commerce international comprennent la lettre de credit lencaissement documentaire le virement bancaire et le paiement anticipe. Pour les nouvelles relations avec les fournisseurs la lettre de credit est la methode la plus sure. Dans les relations commerciales etablies a long terme le compte ouvert ou le paiement echelonne peuvent egalement etre possibles. Toko Trading aide a etablir la structure de paiement la plus adaptee entre le client et le fournisseur.`,ru:`Наиболее распространённые способы оплаты в международной торговле включают аккредитив документарное инкассо банковский перевод и предоплату. При первых отношениях с поставщиком аккредитив является наиболее безопасным методом обеспечивающим защиту как покупателя так и продавца. В установившихся долгосрочных деловых отношениях также возможны расчёты по открытому счёту или оплата в рассрочку. Toko Trading помогает выстроить наиболее подходящую платёжную структуру обеспечивая безопасность обеих сторон.`}},
    {q:{tr:`Turk ${topicTR.toLowerCase()} urunleri hangi kalite standartlarina uygundir`,en:`What quality standards do Turkish ${sectorWord} products comply with`,fr:`A quelles normes de qualite les produits turcs de ${topicFR.toLowerCase()} sont-ils conformes`,ru:`Каким стандартам качества соответствует турецкая продукция ${topicRU.toLowerCase()}`},
     a:{tr:`Turk ureticiler ISO 9001 kalite yonetimi ISO 22000 gida guvenligi ISO 14001 cevre yonetimi HACCP CE isareti ve sektore ozel diger sertifikasyonlara sahiptir. AB Gumruk Birligi anlasmasikapsamnda Turk urunleri AB teknik duzenlemelerine uyumludur. Organik Helal ve diger ozel sertifikalar da talep uzerine saglanabilmektedir. Toko Trading urun bazinda hangi sertifikalarin gerekli oldugu konusunda danismanlik sunmaktadir.`,en:`Turkish manufacturers hold ISO 9001 quality management ISO 22000 food safety ISO 14001 environmental management HACCP CE marking and other sector-specific certifications as standard practice. Under the EU Customs Union agreement Turkish products comply with EU technical regulations ensuring seamless market access. Organic Halal and other specialized certifications can also be provided upon request. Toko Trading offers expert consultation on which specific certifications are required for each product category and destination market.`,fr:`Les fabricants turcs detiennent les certifications ISO 9001 gestion de la qualite ISO 22000 securite alimentaire ISO 14001 gestion environnementale HACCP marquage CE et dautres certifications sectorielles. Dans le cadre de laccord dUnion Douaniere avec lUE les produits turcs sont conformes aux reglementations techniques de lUE. Les certifications biologiques Halal et autres peuvent egalement etre fournies sur demande. Toko Trading offre une consultation experte sur les certifications requises.`,ru:`Турецкие производители имеют сертификаты ISO 9001 управление качеством ISO 22000 безопасность пищевых продуктов ISO 14001 экологический менеджмент HACCP маркировку CE и другие отраслевые сертификаты. В рамках Таможенного союза с ЕС турецкая продукция соответствует техническим регламентам ЕС обеспечивая беспрепятственный доступ на рынок. Органическая сертификация Халяль и другие специализированные сертификаты также могут быть предоставлены по запросу. Toko Trading предлагает экспертную консультацию по необходимым сертификатам.`}},
    {q:{tr:`Turkiyeden ithal edilen ${topicTR.toLowerCase()} urunlerine gumruk vergisi uygulanir mi`,en:`Are customs duties applied to ${sectorWord} products imported from Turkey`,fr:`Des droits de douane sont-ils appliques aux produits de ${topicFR.toLowerCase()} importes de Turquie`,ru:`Применяются ли таможенные пошлины к продукции ${topicRU.toLowerCase()} импортируемой из Турции`},
     a:{tr:`Gumruk vergisi orani hedef ulke ile Turkiye arasindaki ticaret anlasmalarma bagli olarak degismektedir. AB ulkeleri ile Gumruk Birligi sayesinde endustriyel urunlerde gumruk vergisi uygulanmamaktadir. Diger ulkelerde GTIP koduna gore belirlenen vergi oranlari gecerlidir. Serbest ticaret anlasmalari olan ulkelerde indirimli veya sifir gumruk vergisi uygulanabilmektedir. Toko Trading hedef pazardaki guncel vergi oranlari konusunda detayli bilgi saglamaktadir.`,en:`Customs duty rates vary depending on the trade agreements between the destination country and Turkey. With EU countries thanks to the Customs Union agreement no customs duties are applied to industrial products which is a significant advantage. In other countries duty rates determined by HS code apply and these vary by product category. Countries with free trade agreements may benefit from reduced or zero customs duty rates. Toko Trading provides detailed up-to-date information on current duty rates in your specific target market.`,fr:`Les taux de droits de douane varient en fonction des accords commerciaux entre le pays de destination et la Turquie. Avec les pays de lUE grace a laccord dUnion Douaniere aucun droit de douane nest applique aux produits industriels. Dans les autres pays les taux determines par code SH sappliquent. Les pays beneficiant daccords de libre-echange peuvent profiter de taux reduits ou nuls. Toko Trading fournit des informations detaillees et actualisees sur les taux en vigueur.`,ru:`Ставки таможенных пошлин варьируются в зависимости от торговых соглашений между страной назначения и Турцией. Со странами ЕС благодаря Таможенному союзу на промышленные товары таможенные пошлины не применяются что является значительным преимуществом. В других странах действуют ставки определяемые кодом ТН ВЭД. Страны имеющие соглашения о свободной торговле могут пользоваться сниженными или нулевыми ставками. Toko Trading предоставляет подробную актуальную информацию о действующих ставках на вашем целевом рынке.`}},
    {q:{tr:`Toko Trading ${topicTR.toLowerCase()} surecinde nasil yardimci olur`,en:`How does Toko Trading assist in the ${sectorWord} import process`,fr:`Comment Toko Trading aide-t-il dans le processus de ${topicFR.toLowerCase()}`,ru:`Как Toko Trading помогает в процессе ${topicRU.toLowerCase()}`},
     a:{tr:`Toko Trading tedarikci arastirma ve seciminden kalite kontrole belgelendirmeden lojistik yonetimine kadar ithalat surecinin tum asamalarinda profesyonel hizmet sunmaktadir. Deneyimli ekibimiz Turk ureticiler ile uzun yillar icerisinde kurulmus guven iliskilerine sahiptir. Musteri adina fabrika ziyaretleri numune degerlendirmeleri fiyat muzakereleri ve sevkiyat takibi gerceklestirmekteyiz. Tum bu hizmetler tek bir iletisim noktasindan koordine edilmektedir.`,en:`Toko Trading provides professional services throughout all stages of the import process from supplier research and selection to quality control from documentation to logistics management. Our experienced team has established trust relationships with Turkish manufacturers built over many years of successful collaboration. We conduct factory visits sample evaluations price negotiations and shipment tracking on behalf of our clients. All these services are coordinated from a single point of contact for streamlined and efficient communication throughout the process.`,fr:`Toko Trading fournit des services professionnels tout au long de toutes les etapes du processus dimportation de la recherche et selection de fournisseurs au controle qualite de la documentation a la gestion logistique. Notre equipe experimentee a etabli des relations de confiance avec les fabricants turcs construites au fil de nombreuses annees de collaboration reussie. Nous effectuons des visites dusine des evaluations dechantillons des negociations de prix et le suivi des expeditions pour le compte de nos clients.`,ru:`Toko Trading предоставляет профессиональные услуги на всех этапах процесса импорта от поиска и выбора поставщиков до контроля качества от документооборота до управления логистикой. Наша опытная команда имеет устоявшиеся доверительные отношения с турецкими производителями выстроенные за многие годы успешного сотрудничества. Мы проводим посещения фабрик оценку образцов ценовые переговоры и отслеживание отправок от имени наших клиентов. Все эти услуги координируются из единой точки контакта.`}},
    {q:{tr:`${topicTR} sirasinda karsilasilan en yaygin sorunlar nelerdir`,en:`What are the most common challenges during ${sectorWord} importing`,fr:`Quels sont les defis les plus courants lors de ${topicFR.toLowerCase()}`,ru:`Каковы наиболее распространённые проблемы при ${topicRU.toLowerCase()}`},
     a:{tr:`En yaygin sorunlar arasinda dil engeli kalite beklentileri ile gercek urun arasindaki farklilklar gumruk belgelendirme hatalari ve lojistik gecikmeler yer almaktadir. Bunlarin yanisira odeme guvenligi ve fikri mulkiyet korumasi da dikkat edilmesi gereken konulardir. Toko Trading bu riskleri minimize etmek icin uretim oncesi kalite kontrol fabrika denetimi ve kapsamli belgelendirme hizmetleri sunmaktadir. Deneyimimiz bu sorunlarin buyuk cogunlugunun onlenmesine olanak tanmaktadir.`,en:`The most common challenges include language barriers differences between quality expectations and actual products customs documentation errors and logistics delays that can disrupt supply chains. Payment security and intellectual property protection are also areas requiring careful attention. Toko Trading provides pre-production quality control factory inspections and comprehensive documentation services to minimize these risks effectively. Our extensive experience enables us to prevent the vast majority of these issues before they occur.`,fr:`Les defis les plus courants comprennent les barrieres linguistiques les differences entre les attentes de qualite et les produits reels les erreurs de documentation douaniere et les retards logistiques. La securite des paiements et la protection de la propriete intellectuelle sont egalement des domaines necessitant une attention particuliere. Toko Trading fournit un controle qualite pre-production des inspections dusine et des services de documentation complets pour minimiser ces risques de maniere efficace.`,ru:`Наиболее распространённые проблемы включают языковые барьеры расхождения между ожиданиями качества и реальной продукцией ошибки в таможенной документации и логистические задержки. Безопасность платежей и защита интеллектуальной собственности также требуют внимательного подхода. Toko Trading предоставляет предпроизводственный контроль качества фабричные инспекции и комплексные документационные услуги для эффективной минимизации этих рисков. Наш обширный опыт позволяет предотвращать подавляющее большинство этих проблем.`}},
    {q:{tr:`Turkiyeden ${topicTR.toLowerCase()} icin numune talep edebilir miyim`,en:`Can I request samples before placing a full ${sectorWord} import order`,fr:`Puis-je demander des echantillons avant de passer une commande complete de ${topicFR.toLowerCase()}`,ru:`Могу ли я запросить образцы перед размещением полного заказа на ${topicRU.toLowerCase()}`},
     a:{tr:`Evet hemen hemen tum Turk ureticiler siparis oncesi numune gonderimi yapmaktadir. Numune maliyeti genellikle alici tarafindan karsilanir ve siparis onaylandiginda toplam tutardan dusulur. Numune gonderimi kargo ile 3-7 is gunu icerisinde tamamlanmaktadir. Toko Trading numune surecini koordine ederek uygun ureticilerden numune toplanmasini ve karsilastirmali degerlendirme yapilmasini saglamaktadir ve boylece en iyi secimi yapmaniza yardimci olmaktadir.`,en:`Yes virtually all Turkish manufacturers provide pre-order samples for evaluation purposes. Sample costs are generally borne by the buyer and deducted from the total amount when the order is confirmed ensuring no additional expense. Sample delivery is completed within 3 to 7 business days via express courier services. Toko Trading coordinates the entire sampling process collecting samples from suitable manufacturers and facilitating comparative evaluation so you can make the best possible decision for your procurement needs.`,fr:`Oui pratiquement tous les fabricants turcs fournissent des echantillons avant commande a des fins devaluation. Les couts des echantillons sont generalement a la charge de lacheteur et deduits du montant total lors de la confirmation de commande. La livraison des echantillons est completee en 3 a 7 jours ouvrables par courrier express. Toko Trading coordonne lensemble du processus dechantillonnage en collectant des echantillons aupres de fabricants adaptes et en facilitant levaluation comparative pour que vous puissiez prendre la meilleure decision.`,ru:`Да практически все турецкие производители предоставляют образцы до оформления заказа для целей оценки. Стоимость образцов как правило несёт покупатель и вычитается из общей суммы при подтверждении заказа. Доставка образцов осуществляется в течение 3-7 рабочих дней экспресс-курьером. Toko Trading координирует весь процесс отбора образцов собирая образцы от подходящих производителей и обеспечивая сравнительную оценку чтобы вы могли принять наилучшее решение для ваших закупочных потребностей.`}},
    {q:{tr:`${topicTR} icin Turkiyede hangi limanlar ve sinir kapilari kullanilir`,en:`Which ports and border crossings in Turkey are used for ${sectorWord} exports`,fr:`Quels ports et postes frontieres en Turquie sont utilises pour lexportation de ${topicFR.toLowerCase()}`,ru:`Какие порты и пограничные переходы в Турции используются для экспорта ${topicRU.toLowerCase()}`},
     a:{tr:`Turkiyenin baslica ihracat limanlari Mersin Iskenderun Istanbul Ambarli Izmir Aliaga ve Trabzon olup her biri farkli bolgelere hizmet vermektedir. Kara sinir kapilari arasinda Kapikule AB ulkeleri Habur Irak ve Sarp Gurcistan one cikmaktadir. Liman secimi hedef pazara yakinlik urun tipi ve maliyet optimizasyonu gibi faktorlere gore belirlenmektedir. Toko Trading en uygun lojistik rotayi belirleyerek nakliye maliyetlerinizi optimize etmektedir.`,en:`Turkeys main export ports include Mersin Iskenderun Istanbul Ambarli Izmir Aliaga and Trabzon each serving different geographic regions with specialized handling capabilities. Key land border crossings include Kapikule for EU countries Habur for Iraq and Sarp for Georgia providing direct overland access to major markets. Port selection is determined by factors such as proximity to the destination market product type and cost optimization requirements. Toko Trading identifies the most suitable logistics route to optimize your shipping costs and delivery timeline effectively.`,fr:`Les principaux ports dexportation de la Turquie comprennent Mersin Iskenderun Istanbul Ambarli Izmir Aliaga et Trabzon chacun desservant differentes regions geographiques avec des capacites de manutention specialisees. Les principaux postes frontieres terrestres comprennent Kapikule pour les pays de lUE Habur pour lIrak et Sarp pour la Georgie. Le choix du port est determine par des facteurs tels que la proximite du marche de destination le type de produit et les exigences doptimisation des couts. Toko Trading identifie la route logistique la plus adaptee pour optimiser vos couts.`,ru:`Основные экспортные порты Турции включают Мерсин Искендерун Стамбул Амбарлы Измир Алиагу и Трабзон каждый из которых обслуживает различные географические регионы. Ключевые сухопутные пограничные переходы включают Капыкуле для стран ЕС Хабур для Ирака и Сарп для Грузии обеспечивая прямой наземный доступ к основным рынкам. Выбор порта определяется такими факторами как близость к рынку назначения тип продукции и требования оптимизации затрат. Toko Trading определяет наиболее подходящий логистический маршрут для оптимизации ваших транспортных расходов.`}},
  ];

  return { slug, topicEN, topicTR, topicFR, topicRU, questions: qTemplates, links };
}

function genFAQsTS() {
  const faqs = FAQS.map(buildFAQ);
  const lc = (o) => `{ tr: ${JSON.stringify(o.tr)}, en: ${JSON.stringify(o.en)}, fr: ${JSON.stringify(o.fr)}, ru: ${JSON.stringify(o.ru)} }`;

  let ts = `import type { FAQPageData } from './types';\n\nexport const faqPages: FAQPageData[] = [\n`;

  for (const f of faqs) {
    ts += `  {\n    slug: ${JSON.stringify(f.slug)},\n`;
    ts += `    topic: ${lc({tr:f.topicTR,en:f.topicEN,fr:f.topicFR,ru:f.topicRU})},\n`;
    ts += `    meta: {\n`;
    ts += `      title: ${lc({tr:`${f.topicTR} Sik Sorulan Sorular | Toko Trading`,en:`${f.topicEN} Frequently Asked Questions | Toko Trading`,fr:`Questions Frequentes sur ${f.topicFR} | Toko Trading`,ru:`Часто задаваемые вопросы о ${f.topicRU} | Toko Trading`})},\n`;
    ts += `      description: ${lc({tr:`Turkiyeden ${f.topicTR.toLowerCase()} hakkinda en sik sorulan sorular ve detayli yanitlar. Gumruk belgelendirme lojistik ve odeme konularinda kapsamli bilgi.`,en:`Frequently asked questions about ${f.topicEN.toLowerCase()} from Turkey with detailed answers. Comprehensive information on customs documentation logistics and payment terms.`,fr:`Questions frequemment posees sur ${f.topicFR.toLowerCase()} depuis la Turquie avec des reponses detaillees. Informations completes sur les douanes la documentation la logistique et les conditions de paiement.`,ru:`Часто задаваемые вопросы о ${f.topicRU.toLowerCase()} из Турции с подробными ответами. Полная информация о таможне документации логистике и условиях оплаты.`})},\n`;
    ts += `    },\n    content: {\n`;
    ts += `      title: ${lc({tr:`${f.topicTR} Hakkinda Sik Sorulan Sorular`,en:`Frequently Asked Questions About ${f.topicEN}`,fr:`Questions Frequentes sur ${f.topicFR}`,ru:`Часто задаваемые вопросы о ${f.topicRU}`})},\n`;
    ts += `      subtitle: ${lc({tr:`${f.topicTR} surecinde merak edilen tum sorularin kapsamli yanItlari`,en:`Comprehensive answers to all questions about the ${f.topicEN.toLowerCase()} process`,fr:`Reponses completes a toutes les questions sur le processus de ${f.topicFR.toLowerCase()}`,ru:`Исчерпывающие ответы на все вопросы о процессе ${f.topicRU.toLowerCase()}`})},\n`;
    ts += `      intro: ${lc({tr:`Turkiyeden ${f.topicTR.toLowerCase()} surecinyle ilgili en sik sorulan sorulari ve detayli yanitlarini bu sayfada bulabilirsiniz. Gumruk islemleri belgelendirme lojistik planlama odeme yontemleri kalite standartlari ve tedarikci secimi gibi kritik konularda bilgi edinebilirsiniz. Toko Trading olarak yirmi yillik uluslararasi ticaret deneyimimizle musterilerimize her asamada profesyonel rehberlik sunmaktayiz.`,en:`On this page you will find the most frequently asked questions and detailed answers about the ${f.topicEN.toLowerCase()} process from Turkey. You can gain valuable information on critical topics such as customs procedures documentation logistics planning payment methods quality standards and supplier selection. At Toko Trading with over twenty years of international trade experience we provide professional guidance to our clients at every stage of their import journey from Turkey.`,fr:`Sur cette page vous trouverez les questions les plus frequemment posees et les reponses detaillees concernant le processus de ${f.topicFR.toLowerCase()} depuis la Turquie. Vous pouvez obtenir des informations precieuses sur des sujets critiques tels que les procedures douanieres la documentation la planification logistique les methodes de paiement les normes de qualite et la selection des fournisseurs. Chez Toko Trading avec plus de vingt ans dexperience dans le commerce international nous fournissons un accompagnement professionnel a nos clients a chaque etape.`,ru:`На этой странице вы найдёте наиболее часто задаваемые вопросы и подробные ответы о процессе ${f.topicRU.toLowerCase()} из Турции. Вы можете получить ценную информацию по критически важным темам таким как таможенные процедуры документация планирование логистики способы оплаты стандарты качества и выбор поставщиков. В Toko Trading с более чем двадцатилетним опытом международной торговли мы предоставляем профессиональное руководство нашим клиентам на каждом этапе их импортного пути из Турции.`})},\n`;
    ts += `      questions: [\n`;
    for (const qa of f.questions) {
      ts += `        { question: ${lc(qa.q)}, answer: ${lc(qa.a)} },\n`;
    }
    ts += `      ],\n`;
    ts += `      relatedLinks: [\n`;
    for (const link of f.links) {
      ts += `        { label: ${JSON.stringify(link.label)}, href: ${JSON.stringify(link.href)} },\n`;
    }
    ts += `      ],\n    },\n  },\n`;
  }

  ts += `];\n`;

  // Validate word counts
  let minW = Infinity, minS = '', minL = '';
  for (const f of faqs) {
    for (const locale of ['tr','en','fr','ru']) {
      let total = 0;
      // Count all text fields
      total += wc(f.topicEN) + wc(f.topicTR);
      for (const qa of f.questions) {
        total += wc(qa.q[locale]) + wc(qa.a[locale]);
      }
      total += 100; // meta, title, subtitle, intro
      if (total < minW) { minW = total; minS = f.slug; minL = locale; }
    }
  }
  console.log(`  Min word count: ${minW} (${minS} [${minL}])`);
  console.log(`  Total FAQs: ${faqs.length}`);
  return ts;
}

console.log('Generating faqs.ts...');
const faqsTS = genFAQsTS();
fs.writeFileSync(path.join(OUT, 'faqs.ts'), faqsTS, 'utf8');
console.log(`  Written (${faqsTS.length} chars)`);
